<a href="https://colab.research.google.com/github/Quantum256/Athena/blob/main/Deep_Learning_with_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [4]:
#deep learning with keras API
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import random

#MNIST dataset
from keras.datasets import mnist
#Model
from keras.models import Sequential
#layers
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from keras.utils import to_categorical

# Load Dataset

In [5]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()


11490434/11490434 [==============================] - 2s 0us/step


# Preprocess the data

In [6]:
#Normalization of the pixels values
x_train = x_train.astype('float32')/255.0
x_test = x_test.astype('float32')/255.0

#One-Hot Encoder
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

#Add channel dimension for Conv2D
x_train = np.expand_dims(x_train, axis= -1)
x_test = np.expand_dims(x_test, axis= -1)


# Build a Neural Network

In [7]:
model = Sequential()
#layer1
model.add(Conv2D(32,(3,3), activation = 'relu', input_shape =(28, 28, 1)))
model.add(MaxPooling2D((2,2)))
#layer2
model.add(Conv2D(64,(3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))
#layer3
model.add(Conv2D(128,(3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))
#layer4[flatten layer]
model.add(Flatten())
model.add(Dense(128, activation = 'relu'))
#layer5[connecting layers and the 'softmax' layer]
model.add(Dropout(0.5))
model.add(Dense(10, activation = 'softmax'))


# Compile the Model

In [8]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])



# Train the Model

In [9]:
epochs = 20
batch_size = 128

#train the model
model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size, validation_split=0.1)

Epoch 1/20
422/422 [==============================] - 14s 6ms/step - loss: 0.4694 - accuracy: 0.8530 - val_loss: 0.1004 - val_accuracy: 0.9702
Epoch 2/20
422/422 [==============================] - 2s 5ms/step - loss: 0.1446 - accuracy: 0.9579 - val_loss: 0.0675 - val_accuracy: 0.9802
Epoch 3/20
422/422 [==============================] - 2s 5ms/step - loss: 0.0997 - accuracy: 0.9713 - val_loss: 0.0521 - val_accuracy: 0.9857
Epoch 4/20
422/422 [==============================] - 2s 5ms/step - loss: 0.0786 - accuracy: 0.9778 - val_loss: 0.0518 - val_accuracy: 0.9853
Epoch 5/20
422/422 [==============================] - 3s 6ms/step - loss: 0.0643 - accuracy: 0.9815 - val_loss: 0.0485 - val_accuracy: 0.9855
Epoch 6/20
422/422 [==============================] - 2s 5ms/step - loss: 0.0548 - accuracy: 0.9841 - val_loss: 0.0406 - val_accuracy: 0.9892
Epoch 7/20
422/422 [==============================] - 2s 5ms/step - loss: 0.0480 - accuracy: 0.9859 - val_loss: 0.0458 - val_accuracy: 0.9868
Epoch

# Evaluate the Model

In [10]:
loss, accuracy = model.evaluate(x_test, y_test)
print(f'test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}')

313/313 [==============================] - 3s 9ms/step - loss: 0.0566 - accuracy: 0.9878
test loss: 0.0566, Test accuracy: 0.9878


# Make Predictions

In [11]:
predictions = model.predict(x_test[:5])
predicted_labels = np.argmax(predictions, axis=1)
print ('Predicted Label:', predicted_labels)
print ('True Label:', y_test[:5])

1/1 [==============================] - 0s 394ms/step
Predicted Label: [7 2 1 0 4]
True Label: [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
