<a href="https://colab.research.google.com/github/Quantum256/Athena/blob/main/Feature_Extraction_and_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Feature Extractiomn in numerical data
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler

dataX = [[20, 0.3],[30, 0.2],[10, 0.9]]
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(dataX)
print (scaled_data)

[[0.5        0.14285714]
 [1.         0.        ]
 [0.         1.        ]]


In [ ]:
#binning of data
dataX = [[20, 0.3],[30, 0.2],[10, 0.9]]
bins = np.linspace(1,6,4)
binned_data = np.digitize(dataX, bins)

binned_data

array([[4, 0],
       [4, 0],
       [4, 0]])

In [ ]:
#binning of data
dataX = [20, 0.3, 30, 0.2, 10, 0.9]
bins = np.linspace(1,6,4)
binned_data = np.digitize(dataX, bins)

binned_data

array([4, 0, 4, 0, 4, 0])

In [ ]:
#polynomial features used in extracting features in non linear numerical data[high order data]
from sklearn.preprocessing import  PolynomialFeatures

dataY = [[2,3],[2,5],[1,4],[5,3]]
poly = PolynomialFeatures(degree=2)
poly_data = poly.fit_transform(dataY)
poly_data

array([[ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  2.,  5.,  4., 10., 25.],
       [ 1.,  1.,  4.,  1.,  4., 16.],
       [ 1.,  5.,  3., 25., 15.,  9.]])

In [ ]:
#Categorical feature Extraction
from sklearn.preprocessing import OneHotEncoder

colorData = [['red'],['green'],['blue'],['Yellow']]
encoder = OneHotEncoder()
onehot_data = encoder.fit_transform(colorData).toarray()
onehot_data

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [ ]:
#read about targeted enconding
#frequency encoding: assigns a frequency to each categprical value
dataSeries = pd.Series(['mark','walter','paul','mark','keith','martha','keith','martha','mark'])
frequency = dataSeries.value_counts(normalize=True)
encodeSeries = dataSeries.map(frequency)
encodeSeries

0    0.333333
1    0.111111
2    0.111111
3    0.333333
4    0.222222
5    0.222222
6    0.222222
7    0.222222
8    0.333333
dtype: float64

In [ ]:
#label Encoding: assigns each categorical value a number
from sklearn.preprocessing import LabelEncoder

labelData = ['low','high','medium','high','low']
encoder = LabelEncoder()
Labeled_Data = encoder.fit_transform(labelData)
Labeled_Data

array([1, 0, 2, 0, 1])

In [ ]:
#Feature Extraction from text data
#Read about tokenization in natural langauge processing
from sklearn.feature_extraction.text import CountVectorizer

textData = ['how are you','are you okay','that is okay','i am okay','how are you doing']
vector = CountVectorizer()
textExtract = vector.fit_transform(textData)
text = textExtract.todense()
text
# the matrix output is a frequency matrix which represents the number of times a word appear or the number of occurencies of a word.

matrix([[0, 1, 0, 1, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 1, 1, 1, 0],
        [1, 0, 0, 0, 0, 1, 0, 0],
        [0, 1, 1, 1, 0, 0, 0, 1]])

In [ ]:
#Term Freqeuncy Inverse|Document Frequency Inverse
from sklearn.feature_extraction.text import TfidfVectorizer

textData2 = ['how are you','are you okay','that is okay','i am okay','how are you doing']
vector2 = TfidfVectorizer()
textExtract2 = vector2.fit_transform(textData)
text2 = textExtract2.todense()
text2


matrix([[0.        , 0.53828256, 0.        , 0.64846263, 0.        ,
         0.        , 0.        , 0.53828256],
        [0.        , 0.57735027, 0.        , 0.        , 0.        ,
         0.57735027, 0.        , 0.57735027],
        [0.        , 0.        , 0.        , 0.        , 0.63907044,
         0.42799292, 0.63907044, 0.        ],
        [0.83088075, 0.        , 0.        , 0.        , 0.        ,
         0.55645052, 0.        , 0.        ],
        [0.        , 0.41955892, 0.62647696, 0.50543767, 0.        ,
         0.        , 0.        , 0.41955892]])

In [21]:
#word embedding
import gensim
from gensim.models import Word2Vec

textData2 = [['how', 'are', 'you'],['are', 'you', 'okay'],['that', 'is', 'okay'],['i', 'am', 'okay'],['how', 'are', 'you', 'doing']]
model = Word2Vec(textData2, min_count=1)
wordVec = model.wv['that']
wordVec

array([-9.5785465e-03,  8.9431154e-03,  4.1650687e-03,  9.2347348e-03,
        6.6435025e-03,  2.9247368e-03,  9.8040197e-03, -4.4246409e-03,
       -6.8033109e-03,  4.2273807e-03,  3.7290000e-03, -5.6646108e-03,
        9.7047603e-03, -3.5583067e-03,  9.5494064e-03,  8.3472609e-04,
       -6.3384566e-03, -1.9771170e-03, -7.3770545e-03, -2.9795230e-03,
        1.0416972e-03,  9.4826873e-03,  9.3558477e-03, -6.5958775e-03,
        3.4751510e-03,  2.2755705e-03, -2.4893521e-03, -9.2291720e-03,
        1.0271263e-03, -8.1657059e-03,  6.3201892e-03, -5.8000805e-03,
        5.5354391e-03,  9.8337233e-03, -1.6000033e-04,  4.5284927e-03,
       -1.8094003e-03,  7.3607611e-03,  3.9400971e-03, -9.0103243e-03,
       -2.3985039e-03,  3.6287690e-03, -9.9568366e-05, -1.2012708e-03,
       -1.0554385e-03, -1.6716016e-03,  6.0495257e-04,  4.1650953e-03,
       -4.2527914e-03, -3.8336217e-03, -5.2816868e-05,  2.6935578e-04,
       -1.6880632e-04, -4.7855065e-03,  4.3134023e-03, -2.1719194e-03,
      

In [22]:
#image feature extraction
#histogram of oriented gradients

import cv2
image = cv2.imread('/content/Screenshot 2023-09-10 235110.png',0)
hog = cv2.HOGDescriptor()
hog_details = hog.compute(image)
hog_details

array([0.0470809 , 0.26321402, 0.47439966, ..., 0.01107957, 0.09720265,
       0.47748142], dtype=float32)